apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  application.properties: |
    server.port=8082

    spring.application.name=gateway
    spring.profiles.active=test
    management.endpoint.health.probes.enabled=true
